# Generated by Django 4.2.4 on 2023-08-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0002_remove_user_data_company_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='designation',
            field=models.TextField(default='Engineer', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='end_duration',
            field=models.CharField(default='Present', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='job_description',
            field=models.CharField(default='Backend Engineer', max_length=5000),
        ),
        migrations.AddField(
            model_name='company',
            name='start_duration',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='user_data',
            name='email',
            field=models.EmailField(default='abc@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='user_data',
            name='github',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='user_data',
            name='linkedin',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AddField(
            model_name='user_data',
            name='name',
            field=models.TextField(default='Satoshi', max_length=1000),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='ABC Solutions', max_length=200),
        ),
    ]
