# Generated by Django 4.2.4 on 2023-08-23 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv_app', '0003_company_designation_company_end_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='start_duration',
            field=models.DateField(default='2000-12-31'),
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Python', max_length=800)),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(default='ABC Institute', max_length=500)),
                ('degree', models.CharField(default="Bachelor's", max_length=400)),
                ('start_duration', models.IntegerField(default=2000)),
                ('end_duration', models.CharField(default='Present', max_length=100)),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Certificate Name', max_length=2000)),
                ('issuer', models.CharField(default='Issuer Name', max_length=600)),
                ('issueDate', models.DateField(default='2000-12-31')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
